"""
Curried versions of Python's operator module functions.

Binary and n-ary operators are curried to support partial application.
Unary operators are not curried (since they only take one argument).

From a typing perspective, curried functions have identical signatures
to their uncurried versions, so we simply re-export from operator.
"""

from operator import (
    __abs__ as __abs__,
    __add__ as __add__,
    __and__ as __and__,
    __call__ as __call__,
    __concat__ as __concat__,
    __contains__ as __contains__,
    __delitem__ as __delitem__,
    __eq__ as __eq__,
    __floordiv__ as __floordiv__,
    __ge__ as __ge__,
    __getitem__ as __getitem__,
    __gt__ as __gt__,
    __iadd__ as __iadd__,
    __iand__ as __iand__,
    __iconcat__ as __iconcat__,
    __ifloordiv__ as __ifloordiv__,
    __ilshift__ as __ilshift__,
    __imatmul__ as __imatmul__,
    __imod__ as __imod__,
    __imul__ as __imul__,
    __index__ as __index__,
    __inv__ as __inv__,
    __invert__ as __invert__,
    __ior__ as __ior__,
    __ipow__ as __ipow__,
    __irshift__ as __irshift__,
    __isub__ as __isub__,
    __itruediv__ as __itruediv__,
    __ixor__ as __ixor__,
    __le__ as __le__,
    __lshift__ as __lshift__,
    __lt__ as __lt__,
    __matmul__ as __matmul__,
    __mod__ as __mod__,
    __mul__ as __mul__,
    __ne__ as __ne__,
    __neg__ as __neg__,
    __not__ as __not__,
    __or__ as __or__,
    __pos__ as __pos__,
    __pow__ as __pow__,
    __rshift__ as __rshift__,
    __setitem__ as __setitem__,
    __sub__ as __sub__,
    __truediv__ as __truediv__,
    __xor__ as __xor__,
    abs as abs,
    add as add,
    and_ as and_,
    attrgetter as attrgetter,
    call as call,
    concat as concat,
    contains as contains,
    countOf as countOf,
    delitem as delitem,
    eq as eq,
    floordiv as floordiv,
    ge as ge,
    getitem as getitem,
    gt as gt,
    iadd as iadd,
    iand as iand,
    iconcat as iconcat,
    ifloordiv as ifloordiv,
    ilshift as ilshift,
    imatmul as imatmul,
    imod as imod,
    imul as imul,
    index as index,
    indexOf as indexOf,
    inv as inv,
    invert as invert,
    ior as ior,
    ipow as ipow,
    irshift as irshift,
    is_ as is_,
    is_not as is_not,
    isub as isub,
    itemgetter as itemgetter,
    itruediv as itruediv,
    ixor as ixor,
    le as le,
    length_hint as length_hint,
    lshift as lshift,
    lt as lt,
    matmul as matmul,
    methodcaller as methodcaller,
    mod as mod,
    mul as mul,
    ne as ne,
    neg as neg,
    not_ as not_,
    or_ as or_,
    pos as pos,
    pow as pow,
    rshift as rshift,
    setitem as setitem,
    sub as sub,
    truediv as truediv,
    truth as truth,
    xor as xor,
)
