"""
This type stub file was generated by pyright.
"""

from .itertoolz import *
from .functoolz import *
from .dicttoolz import *
from .recipes import *
from functools import partial, reduce
from . import curried, sandbox

sorted = ...
map = map
filter = filter
comp = ...
def __getattr__(name): # -> str:
    ...

